export interface CoreServiceSection {
  title: string;
  items: string[];
}

export interface CoreServiceItem {
  id: string;
  number: number;
  slug: string;
  titleEn: string;
  titleAr: string;
  taglineEn: string;
  taglineAr: string;
  iconName: string;
  overviewEn: string;
  overviewAr: string;
  sections: CoreServiceSection[];
}

export const CORE_SERVICES_DATA: CoreServiceItem[] = [
  {
    id: "company-formation",
    number: 1,
    slug: "company-formation-setup",
    titleEn: "Company Formation & Business Setup Services",
    titleAr: "تأسيس الشركات وخدمات بدء الأعمال",
    taglineEn: "Complete Business Setup — From Company Formation to Operational Support.",
    taglineAr: "تأسيس متكامل للشركات — من مرحلة التأسيس وحتى التشغيل الكامل.",
    iconName: "Building2",
    overviewEn: "End-to-end corporate formation services in the Kingdom of Bahrain. We assist international and local investors with 100% foreign ownership, Commercial Registration (CR), licensing, office address, and complete operational readiness.",
    overviewAr: "خدمات شاملة لتأسيس الشركات في مملكة البحرين للمستثمرين المحليين والدوليين مع ملكية أجنبية 100%، إصدار السجل التجاري، التراخيص والمقرات.",
    sections: [
      {
        title: "Company Setup & Registration",
        items: [
          "Company Formation & Registration",
          "Commercial Registration (CR) Assistance",
          "W.L.L. Company Formation (With Limited Liability)",
          "Sole Proprietorship Registration",
          "Partnership & Corporate Structure Setup",
          "Foreign Investor Company Setup",
          "100% Foreign Ownership Assistance",
          "Business Activity & License Selection",
          "Municipality & Regulatory Approvals",
        ],
      },
      {
        title: "Operational & Infrastructure Setup",
        items: [
          "LMRA Registration & Labour File Setup",
          "Visa & Work Permit Assistance",
          "Visa Quota / Ceiling Assistance",
          "Office & Commercial Address Facility",
          "EWA Connection / Office Facility",
          "Bank Account Opening Assistance",
          "Corporate Bank Account Assistance",
          "Bank Deposit Facility Assistance",
        ],
      },
      {
        title: "Government Liaison & Compliance",
        items: [
          "MOIC Registration & Approvals",
          "Sijilat Registration & Services",
          "Accounting & Bookkeeping Services",
          "VAT Registration & Compliance",
          "Tax & Financial Consultation",
          "Annual CR Renewal",
          "License Renewal & Amendments",
          "Company Name Reservation",
          "Shareholder & Partner Changes",
          "Manager / Authorized Signatory Changes",
          "Branch Registration",
          "Business Activity Addition / Modification",
          "Company Transfer & Ownership Changes",
          "Legal Documentation & Agreements",
          "Employment Contract Assistance",
          "Government & Regulatory Liaison",
          "Company Closure / Deregistration",
          "Ongoing Corporate & Business Support",
        ],
      },
    ],
  },
  {
    id: "cr-services",
    number: 2,
    slug: "commercial-registration-services",
    titleEn: "Commercial Registration (CR) Services – Bahrain",
    titleAr: "خدمات السجل التجاري (CR) – البحرين",
    taglineEn: "Complete CR Management, Renewals, Amendments & Consultancy.",
    taglineAr: "إدارة شاملة للسجلات التجارية، التجديد، التعديلات والاستشارات.",
    iconName: "FileCheck2",
    overviewEn: "Professional management of Bahrain Commercial Registrations (CR). From new registrations and amendments to activity changes, share transfers, and government renewals.",
    overviewAr: "إدارة متخصصة للسجلات التجارية بمملكة البحرين، تشمل التأسيس الجديد، التعديلات، نقل الحصص وتجديد التراخيص.",
    sections: [
      {
        title: "CR Applications & Amendments",
        items: [
          "New CR Registration",
          "CR Renewal",
          "CR Amendment",
          "CR Activity Addition",
          "CR Activity Removal",
          "Business Activity Change",
          "Company Name Reservation",
          "Company Name Change",
          "Legal Form Change",
          "Sole Proprietorship CR",
          "W.L.L. Company CR",
          "Partnership Company Registration",
          "Branch CR Registration",
          "Foreign Company Branch Registration",
          "100% Foreign Ownership CR Assistance",
        ],
      },
      {
        title: "Ownership, Address & Status Changes",
        items: [
          "Shareholder Addition / Removal",
          "Share Transfer & Ownership Change",
          "Manager / Authorized Signatory Change",
          "Address Change",
          "Commercial Address Registration",
          "Office Address Update",
          "CR Suspension",
          "CR Reactivation",
          "CR Cancellation / Closure",
          "Branch Closure",
          "Company Conversion",
          "CR Status & Information Update",
        ],
      },
      {
        title: "Government Liaison & Legal Documentation",
        items: [
          "MOIC Approvals & Registration",
          "Sijilat Services",
          "Municipality Approval Assistance",
          "Required Government Approvals",
          "Bank Account Opening Assistance",
          "LMRA Registration Assistance",
          "Labour File Opening",
          "Visa Quota / Ceiling Assistance",
          "EWA & Office Facility Assistance",
          "Company Documents & Certificates",
          "Commercial Registration Extract / Print",
          "Memorandum of Association (MOA) Assistance",
          "Articles & Corporate Documentation",
          "Annual Renewal & Compliance",
          "Government Liaison & Follow-up",
          "Complete CR Management & Consultancy",
        ],
      },
    ],
  },
  {
    id: "moic-sijilat",
    number: 3,
    slug: "moic-sijilat-government-services",
    titleEn: "MOIC & Sijilat Government Services – Bahrain",
    titleAr: "خدمات وزارة التجارة وسجلات الحكومية – البحرين",
    taglineEn: "MOIC • Sijilat • CR • Government Approvals — Complete Business & Corporate Support in Bahrain",
    taglineAr: "وزارة التجارة • سجلات • السجل التجاري • الموافقات الحكومية — دعم متكامل في البحرين",
    iconName: "Landmark",
    overviewEn: "Direct expertise in Ministry of Industry & Commerce (MOIC) and Sijilat online portal operations for fast-track business processing and regulatory approvals.",
    overviewAr: "خبرة متخصصة في منصة سجلات ووزارة الصناعة والتجارة لتسريع إنجاز المعاملات والحصول على الموافقات الرسمية.",
    sections: [
      {
        title: "Sijilat & MOIC Corporate Filings",
        items: [
          "Commercial Registration (CR) New Registration",
          "CR Renewal",
          "CR Amendment & Modification",
          "Business Activity Addition / Removal",
          "Business Activity Change",
          "Commercial Name Reservation",
          "Commercial Name Change",
          "Legal Form Change",
          "Company Formation & Registration",
          "W.L.L. Registration",
          "Sole Proprietorship Registration",
          "Branch Registration",
          "Foreign Company Branch Registration",
          "Shareholder Addition / Removal",
          "Share Transfer & Ownership Change",
          "Manager / Authorized Signatory Change",
        ],
      },
      {
        title: "Approvals & Online Application Follow-Up",
        items: [
          "Commercial Address Change",
          "Branch Address Update",
          "Company Conversion",
          "CR Suspension & Reactivation",
          "CR Cancellation / Closure",
          "Branch Closure",
          "MOA / Company Agreement Assistance",
          "Articles & Corporate Documents",
          "Municipality Approval Coordination",
          "Government Authority Approvals",
          "Activity-Specific License Approvals",
          "Foreign Ownership / Investor Assistance",
          "Sijilat Online Applications",
          "Sijilat Account & Application Assistance",
          "CR Extract / Certificate Services",
          "Commercial Registration Information Update",
          "Company & Partner Information Updates",
          "Annual CR Renewal & Compliance",
          "Government Fee & Application Assistance",
          "Application Status Follow-up",
          "Pending / Rejected Application Assistance",
          "Government Correspondence & Follow-up",
          "Complete MOIC & Sijilat Consultancy",
        ],
      },
    ],
  },
  {
    id: "lmra-services",
    number: 4,
    slug: "lmra-services-labour-solutions",
    titleEn: "LMRA Services & Labour Market Solutions – Bahrain",
    titleAr: "خدمات هيئة تنظيم سوق العمل (LMRA) والحلول العمالية",
    taglineEn: "Complete Labour Market Solutions, Work Permits & Inspection Offence Removal.",
    taglineAr: "حلول شاملة لسوق العمل، تصاريح العمل، وإزالة مخالفات التفتيش.",
    iconName: "Users2",
    overviewEn: "Comprehensive Labour Market Regulatory Authority (LMRA) solutions. We manage labour files, work permits, visa ceilings, ceiling increases, investor visas, and inspection offence clearance.",
    overviewAr: "حلول متكاملة لهيئة تنظيم سوق العمل تشمل فتح الملفات، تصاريح العمل، رفع سقف التأشيرات وإزالة المخالفات.",
    sections: [
      {
        title: "Work Permits & Visa Ceiling",
        items: [
          "LMRA New Registration",
          "Labour File Opening",
          "Employer / Establishment Registration",
          "Work Permit Applications",
          "New Work Permit Processing",
          "Work Permit Renewal",
          "Work Permit Cancellation",
          "Work Permit Transfer",
          "Employee Transfer Services",
          "Expatriate Employee Registration",
          "Work Visa / Employment Visa Assistance",
          "Visa Quota / Ceiling Applications",
          "Visa Quota Increase",
          "Investor Visa Assistance",
          "Employee Visa Assistance",
          "Domestic / Commercial Work Permit Guidance",
          "Employee Status & Permit Updates",
          "Occupation / Job Title Change Assistance",
          "Employer & Employee Record Updates",
          "Passport / CPR Information Updates",
          "Employment Contract Assistance",
        ],
      },
      {
        title: "LMRA Inspection & Offence Clearance",
        items: [
          "LMRA Inspection Offence Assistance",
          "Inspection Offence Removal / Clearance Assistance",
          "Workload Offence Assistance",
          "Workload Offence Removal / Clearance Assistance",
          "LMRA Compliance Issue Resolution",
          "Inspection Report Review & Follow-up",
          "Offence Status Follow-up with LMRA",
          "Corrective Action & Compliance Support",
          "Pending LMRA Offence Resolution Assistance",
          "Establishment Compliance Regularization",
          "Labour Market Regulatory Compliance",
          "LMRA Inspection & Compliance Assistance",
          "Inspection Issue / Offence Follow-up",
          "Administrative & Compliance Support",
          "Overstay / Permit Issue Guidance",
          "Absconding-Related Case Assistance",
          "Work Permit Cancellation & Finalization",
          "Employee Departure / Exit Process Assistance",
          "Bahrainization / Workforce Compliance Guidance",
          "Wage & Employment Documentation Support",
          "Monthly Salary / Employment Record Assistance",
          "Government Application Follow-up",
          "LMRA Online Services Assistance",
          "LMRA Account & Application Support",
          "Application Status Follow-up",
          "Pending / Rejected Application Assistance",
          "Labour Market Regulatory Consultancy",
          "Complete Labour Market Solutions for Businesses",
        ],
      },
    ],
  },
  {
    id: "immigration-visas",
    number: 5,
    slug: "immigration-visa-consultancy",
    titleEn: "Immigration & Visa Consultancy Services – Bahrain & Worldwide",
    titleAr: "استشارات الهجرة والتأشيرات – البحرين وحول العالم",
    taglineEn: "Professional Worldwide Travel Visa Assistance for Tourists, Families, Business Travellers and GCC Residents.",
    taglineAr: "مساعدة احترافية في التأشيرات السياحية والعائلية وتأشيرات رجال الأعمال ومقيمي الخليج.",
    iconName: "Compass",
    overviewEn: "Global visa facilitation and Bahrain immigration services. We assist with Schengen, UK, USA, Canada, Australia, GCC, and 50+ international destinations with biometric appointments, documentation, and interview preparation.",
    overviewAr: "تسهيل استخراج التأشيرات العالمية لكافة الوجهات (الشنغن، بريطانيا، أمريكا، كندا، الخليج) مع حجز المواعيد وتجهيز الملفات.",
    sections: [
      {
        title: "Worldwide Visa Consultancy",
        items: [
          "Visit Visa Consultancy",
          "Tourist Visa Consultancy",
          "Business Visa Consultancy",
          "Family Visit Visa Assistance",
          "Family Residence Visa Assistance",
          "Employment / Work Visa Consultancy",
          "Investor Visa Consultancy",
          "Residence Visa Assistance",
          "Multiple-Entry Visa Consultancy",
          "Schengen Visa Consultancy",
          "UK Visa Consultancy",
          "USA Visa Consultancy",
          "Canada Visa Consultancy",
          "Australia Visa Consultancy",
          "New Zealand Visa Consultancy",
          "Europe Visa Consultancy",
          "GCC Visa Consultancy (Saudi, UAE, Qatar, Oman, Kuwait)",
          "Turkey, Malaysia, Thailand, Azerbaijan, Georgia Visas",
          "Spain, Italy, France, Germany, Greece, Portugal Visas",
        ],
      },
      {
        title: "Application, Booking & Refusal Support",
        items: [
          "Visa Eligibility Assessment",
          "Visa Category Selection",
          "Application Preparation & Form Filling",
          "Online Visa Application Assistance",
          "Appointment Booking Assistance",
          "Document Checklist & Verification",
          "Cover Letter & Travel Itinerary Preparation",
          "Hotel & Flight Reservation Assistance",
          "Travel Insurance Assistance",
          "Invitation Letter & Sponsorship Guidance",
          "Financial & Bank Statement Guidance",
          "Employment & Salary Documentation",
          "FRC / Family Documentation Guidance",
          "Biometric Appointment Assistance",
          "Interview Preparation",
          "Visa Application Submission Guidance",
          "Application Status Tracking & Embassy Follow-up",
          "Visa Refusal Assessment & Re-application Guidance",
          "Visa Extension & Renewal Guidance",
        ],
      },
      {
        title: "Bahrain Immigration & NPRA Services",
        items: [
          "Bahrain Visit Visa Assistance",
          "Bahrain Residence Visa Assistance",
          "Investor Visa Assistance",
          "Employment Visa Assistance",
          "Family Visa Assistance",
          "Visa Renewal & Cancellation",
          "Visa Transfer Guidance",
          "Immigration Status & Application Support",
          "NPRA-Related Application Assistance",
          "GCC Resident Visa Consultancy",
        ],
      },
    ],
  },
  {
    id: "legal-corporate",
    number: 6,
    slug: "legal-corporate-support",
    titleEn: "Legal & Corporate Support Services – Bahrain",
    titleAr: "الخدمات القانونية والدعم المؤسسي – البحرين",
    taglineEn: "Professional Assistance for Company Formation, Contracts, Compliance & Corporate Documentation in Bahrain.",
    taglineAr: "مساعدة مهنية في صياغة العقود، الامتثال القانوني، التوثيق المؤسسي وحماية الأعمال.",
    iconName: "Scale",
    overviewEn: "Corporate legal consulting, MOA/AOA drafting, contract review, dispute resolution guidance, and international investor legal structuring.",
    overviewAr: "استشارات قانونية مؤسسية، صياغة وتوثيق عقود التأسيس، مراجعة الاتفاقيات التجارية، وحماية حقوق المستثمرين.",
    sections: [
      {
        title: "Corporate Legal Services",
        items: [
          "Company Formation & Legal Structuring",
          "W.L.L. & Corporate Structure Advisory",
          "Partnership & Shareholding Agreements",
          "Memorandum of Association (MOA) Assistance",
          "Articles of Association (AOA) Assistance",
          "Shareholders’ Agreements",
          "Corporate Resolutions",
          "Board & Shareholder Resolutions",
          "Company Policies & Internal Documentation",
          "Corporate Governance Support",
          "Corporate Due Diligence",
          "Legal Compliance Guidance",
        ],
      },
      {
        title: "Contracts, Agreements & Commercial Transactions",
        items: [
          "Employment Agreements",
          "Business Partnership Agreements",
          "Share Purchase / Transfer Agreements",
          "Service & Consultancy Agreements",
          "Supplier & Vendor Agreements",
          "Distribution Agreements",
          "Non-Disclosure Agreements (NDA)",
          "Non-Compete Agreements",
          "Lease / Tenancy Agreement Guidance",
          "General Commercial Contracts",
          "Contract Review & Drafting Assistance",
          "Share Transfer Assistance",
          "Shareholder & Manager Changes",
          "Company Restructuring & Business Transfer",
          "Branch Registration & Closure",
          "Company Merger / Conversion Guidance",
          "Company Closure & Deregistration",
        ],
      },
      {
        title: "Dispute & Foreign Investor Legal Support",
        items: [
          "Commercial Dispute Assistance",
          "Contract Dispute Guidance",
          "Employment Dispute Guidance",
          "Labour-Related Legal Support",
          "Payment & Debt Recovery Guidance",
          "Legal Notice Preparation Assistance",
          "Settlement & Negotiation Support",
          "Mediation / Arbitration Guidance",
          "Litigation Referral & Coordination with Licensed Lawyers",
          "Foreign Investor Legal Guidance",
          "Foreign Ownership Structuring",
          "Cross-Border Contract Assistance",
          "Power of Attorney Documentation Guidance",
          "Annual Corporate Compliance & Record Management",
        ],
      },
    ],
  },
  {
    id: "banking-assistance",
    number: 7,
    slug: "bank-account-banking-assistance",
    titleEn: "Bank Account & Banking Assistance – Bahrain",
    titleAr: "فتح الحسابات البنكية والخدمات المصرفية – البحرين",
    taglineEn: "Corporate & Personal Banking Solutions with Top Bahrain & Global Banks.",
    taglineAr: "حلول مصرفية متكاملة لفتح الحسابات التجارية والشخصية مع كبرى البنوك.",
    iconName: "Landmark",
    overviewEn: "End-to-end support for corporate bank account opening for W.L.L. companies, sole proprietorships, foreign investors, non-residents, and SME financing.",
    overviewAr: "تسهيل فتح الحسابات المصرفية للشركات ذات المسؤولية المحدودة والمؤسسات الفردية والمستثمرين الأجانب مع تجهيز ملفات الامتثال (KYC).",
    sections: [
      {
        title: "Corporate & Business Banking",
        items: [
          "Corporate Bank Account Opening Assistance",
          "Business Bank Account Opening",
          "W.L.L. Corporate Account Assistance",
          "Sole Proprietorship Account Assistance",
          "SME Banking Solutions",
          "Corporate Current Account Assistance",
          "Corporate Savings Account Assistance",
          "Multi-Currency Account Guidance",
          "Foreign Investor Banking Assistance",
          "Non-Resident / Overseas Shareholder Banking Guidance",
          "Business Banking Documentation Preparation",
          "Bank KYC Documentation Support",
        ],
      },
      {
        title: "Personal Banking & Payment Solutions",
        items: [
          "Personal Bank Account Opening Assistance",
          "Current & Savings Account Assistance",
          "Expatriate Banking Guidance",
          "Salary Account Assistance",
          "Non-Resident Banking Guidance",
          "GCC Resident Banking Assistance",
          "Debit Card & Credit Card Application Guidance",
          "Business Debit Card Assistance",
          "Cheque Book Assistance",
          "Online / Mobile Banking Setup Guidance",
          "POS Machine / Merchant Account Assistance",
          "Payment Gateway Assistance & Online Solutions",
          "International & Local Transfer Guidance",
          "Foreign Currency Exchange Guidance",
        ],
      },
      {
        title: "Business Financing & Bank Compliance",
        items: [
          "Business Loan Application Guidance",
          "SME Financing Assistance",
          "Working Capital Finance Guidance",
          "Trade Finance & Bank Guarantee Guidance",
          "Letter of Credit (LC) Assistance",
          "Overdraft Facility Guidance",
          "Corporate Credit Facility Guidance",
          "Bank Deposit Facility Assistance",
          "Bank Application Forms Preparation",
          "KYC / AML Documentation Assistance",
          "Source of Funds & Wealth Documentation Guidance",
          "Company Profile & Business Plan Preparation",
          "Shareholder & UBO Documentation",
          "Bank Compliance Query Assistance",
          "Signatory & Shareholder Change Assistance",
          "Dormant Account Reactivation Guidance",
        ],
      },
    ],
  },
  {
    id: "business-licensing",
    number: 8,
    slug: "business-licensing-regulatory-support",
    titleEn: "Business Licensing & Regulatory Support – Bahrain",
    titleAr: "التراخيص التجارية والدعم التنظيمي – البحرين",
    taglineEn: "Business Licensing • MOIC • Sijilat • Regulatory Approvals • Compliance • Government Liaison",
    taglineAr: "التراخيص التجارية • وزارة التجارة • سجلات • الموافقات التنظيمية • الامتثال الحكومي",
    iconName: "ShieldCheck",
    overviewEn: "Complete licensing solutions across all ministries and regulatory bodies in Bahrain including Municipality, Civil Defence, Health, Tourism, and Environmental authorities.",
    overviewAr: "استخراج كافة التراخيص التجارية والموافقات من مختلف الوزارات والهيئات التنظيمية في البحرين والبلديات والدفاع المدني.",
    sections: [
      {
        title: "Business Licensing Services",
        items: [
          "New Business License Assistance",
          "Commercial Registration (CR) Licensing",
          "Business Activity Selection",
          "Business Activity Addition / Removal",
          "License Renewal",
          "License Amendment & Modification",
          "License Transfer Assistance",
          "License Suspension & Reactivation",
          "License Cancellation / Closure",
          "Branch License Assistance",
          "Foreign Company Branch Licensing",
          "Home-Based / Special Activity Licensing Guidance",
          "Professional & Commercial License Assistance",
        ],
      },
      {
        title: "Government & Regulatory Approvals",
        items: [
          "MOIC Approval Assistance",
          "Sijilat Application Support",
          "Municipality Approval Assistance",
          "LMRA Registration & Compliance",
          "NPRA-Related Regulatory Assistance",
          "EWA-Related Business Requirements",
          "Civil Defence / Safety Approval Coordination",
          "Health & Safety Approval Guidance",
          "Environment-Related Approval Guidance",
          "Activity-Specific Government Approvals",
          "Regulatory Authority Application Follow-up",
          "Foreign Investor Business Setup & Structuring",
          "100% Foreign Ownership Assistance",
        ],
      },
      {
        title: "Premises Licensing & Compliance",
        items: [
          "Commercial Address Registration",
          "Office / Shop Licensing Assistance",
          "Municipality Site Approval Guidance",
          "EWA Connection Assistance",
          "Office Facility Documentation",
          "Lease / Tenancy Documentation Guidance",
          "Signboard / Commercial Signage Approval Guidance",
          "Operational Permit Assistance",
          "Business License Compliance Review",
          "Government Inspection Preparation",
          "Regulatory Issue Resolution Support",
          "Annual Compliance & Monitoring",
        ],
      },
    ],
  },
  {
    id: "investor-entrepreneur",
    number: 9,
    slug: "investor-entrepreneur-support",
    titleEn: "Investor & Entrepreneur Support Services – Bahrain",
    titleAr: "دعم المستثمرين ورواد الأعمال – البحرين",
    taglineEn: "End-to-End Startup, Investor Residency & Business Infrastructure Setup in Bahrain.",
    taglineAr: "دعم متكامل للشركات الناشئة، إقامات المستثمرين، وتجهيز البنية التحتية للأعمال.",
    iconName: "Rocket",
    overviewEn: "VIP investor onboarding and startup advisory. We provide turnkey market entry, investor residency, office infrastructure, feasibility guidance, and ongoing growth support.",
    overviewAr: "خدمات كبار المستثمرين والشركات الناشئة لدخول السوق البحريني بنجاح، تشمل إقامات المستثمرين، المكاتب، والحلول المالية.",
    sections: [
      {
        title: "Business Setup & Foreign Investor Services",
        items: [
          "New Company Formation",
          "Commercial Registration (CR) Assistance",
          "W.L.L. Company Formation",
          "Sole Proprietorship Setup",
          "Partnership & Corporate Structure",
          "Foreign Investor Company Setup",
          "100% Foreign Ownership Guidance Where Permitted",
          "Business Activity Selection & Name Reservation",
          "Branch Registration & Restructuring",
          "Foreign Investor Setup Assistance",
          "Investor Residency / Visa Guidance",
          "Shareholder & Partner Registration",
          "Share Transfer Assistance",
          "UBO / Beneficial Ownership Registration",
          "Foreign Ownership Structuring",
          "Corporate Bank Account Opening Guidance",
        ],
      },
      {
        title: "Entrepreneur, Startup & Financial Support",
        items: [
          "Startup Business Setup & Activity Consultation",
          "Business Model Guidance & Planning",
          "Business Plan Preparation",
          "Feasibility Study Coordination",
          "Market Entry Guidance & Advisory",
          "Startup Licensing Assistance",
          "SME Setup Support",
          "Corporate Bank Account Assistance",
          "Business Banking Solutions",
          "Bank KYC & Source of Wealth Documentation",
          "Merchant / POS & Payment Gateway Setup",
          "Business Financing Guidance",
          "Working Capital Finance Guidance",
          "Bank Deposit Facility Assistance",
        ],
      },
      {
        title: "Infrastructure & Growth Support",
        items: [
          "Office Facility Assistance",
          "Commercial Address & EWA Facility",
          "Business Premises Guidance",
          "Municipality Approval Assistance",
          "Commercial Lease Documentation Guidance",
          "LMRA Registration & Labour File Opening",
          "Work Permit & Investor Visa Assistance",
          "MOA & Corporate Agreements",
          "Corporate Governance Support",
          "MOIC & Sijilat Government Approvals",
          "Inspection & Compliance Support",
          "Business Expansion Planning & Ongoing Support",
        ],
      },
    ],
  },
  {
    id: "ongoing-corporate",
    number: 10,
    slug: "ongoing-corporate-government-services",
    titleEn: "Ongoing Corporate & Government Services – Bahrain",
    titleAr: "الخدمات المؤسسية والمتابعة الحكومية المستمرة – البحرين",
    taglineEn: "One Partner for Your Business — Corporate Maintenance, Government Services, LMRA, MOIC, Banking, Licensing & Ongoing Compliance Support in Bahrain.",
    taglineAr: "شريك واحد لأعمالك — الصيانة المؤسسية، الخدمات الحكومية، هيئة تنظيم سوق العمل، وزارة التجارة، التراخيص والامتثال الدائم.",
    iconName: "Briefcase",
    overviewEn: "Dedicated corporate retainer and operational maintenance. We handle annual CR renewals, MOIC filings, LMRA offences, bank compliance, and day-to-day government liaison so your business runs without disruption.",
    overviewAr: "المتابعة المؤسسية الدائمة للشركات تشمل تجديد السجلات، متابعة معاملات الهيئة والوزارات، البنوك، وإدارة الالتزامات القانونية.",
    sections: [
      {
        title: "Corporate Maintenance & Compliance",
        items: [
          "CR Renewal & Maintenance",
          "Business License Renewal",
          "Business Activity Updates",
          "Company Information Updates",
          "Shareholder / Partner Updates",
          "Manager / Authorized Signatory Changes",
          "UBO Information Updates",
          "Corporate Record Maintenance",
          "Company Document Updates",
          "Corporate Compliance Support",
          "Annual Compliance Assistance",
          "Company Status Monitoring",
        ],
      },
      {
        title: "Government Services & Follow-Up",
        items: [
          "MOIC Government Services",
          "Sijilat Services",
          "CR Government Services",
          "LMRA Services",
          "NPRA-Related Assistance",
          "Municipality Services",
          "EWA-Related Business Services",
          "Government Approval Coordination",
          "Government Application Submission",
          "Application Status Tracking",
          "Government Correspondence & Follow-Up",
          "Pending Application Follow-Up",
          "Rejected Application Assistance",
        ],
      },
      {
        title: "LMRA, Banking, Operations & Advisory",
        items: [
          "Labour File Maintenance",
          "Work Permit Renewal & Cancellation",
          "Employee Transfer Assistance",
          "Visa Quota / Ceiling Assistance",
          "Visa Quota Increase Support",
          "Investor Visa Assistance",
          "Inspection Follow-Up & Offence Assistance",
          "Offence Clearance / Removal Assistance",
          "Corporate Bank Account Support & KYC Updates",
          "Authorized Signatory & UBO Updates",
          "Corporate Documentation & Contracts",
          "Commercial Address & EWA Facility Updates",
          "Ongoing Business Transformation & Advisory",
        ],
      },
    ],
  },
];
