export interface VisaDetail {
  slug: string;
  name: string;
  country: string;
  flag: string;
  region: "europe" | "gcc" | "asia" | "americas" | "africa";
  regionName: string;
  type: string;
  time: string;
  entryType: string;
  validity: string;
  heroImage: string;
  cardImage: string;
  tagline: string;
  overview: string;
  requirements: string[];
  processSteps: { step: string; title: string; desc: string }[];
  included: string[];
}

export const allVisasData: VisaDetail[] = [
  {
    slug: "malaysia",
    name: "Malaysia Tourist & eVisa",
    country: "Malaysia",
    flag: "🇲🇾",
    region: "asia",
    regionName: "Southeast Asia",
    type: "Tourist & Business eVisa",
    time: "3 - 5 Business Days",
    entryType: "Single & Multiple Entry",
    validity: "30 - 90 Days",
    heroImage: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=700&q=80&auto=format&fit=crop",
    tagline: "Explore Kuala Lumpur, Penang, and Langkawi with Fast-Track eVisa Approvals",
    overview: "Arizona provides end-to-end Malaysia visa processing with verified documentation, flight itinerary reservation, and electronic visa issuance directly to your email.",
    requirements: [
      "Original Passport valid for at least 6 months",
      "Recent passport-size photograph with white background",
      "Confirmed round-trip flight booking voucher",
      "Confirmed hotel reservation in Malaysia",
      "Bank statement showing sufficient travel funds",
    ],
    processSteps: [
      { step: "01", title: "Submit Passport & Photo", desc: "Send your scanned documents via WhatsApp or visit our office." },
      { step: "02", title: "Application Verification", desc: "Our visa specialists review and file your application with Malaysian Immigration." },
      { step: "03", title: "Receive eVisa PDF", desc: "Receive your official approved eVisa document within 3-5 working days." },
    ],
    included: ["Official Immigration Fee Submission", "Flight & Hotel Vouchers", "24/7 Application Status Tracking"],
  },
  {
    slug: "spain",
    name: "Spain (Schengen Area) Visa",
    country: "Spain",
    flag: "🇪🇸",
    region: "europe",
    regionName: "Europe",
    type: "Short-Stay Tourist / Business (Type C)",
    time: "15 - 20 Working Days",
    entryType: "Single / Multi Entry (27 Schengen Countries)",
    validity: "Up to 90 Days within 180-day period",
    heroImage: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=700&q=80&auto=format&fit=crop",
    tagline: "Travel Across 27 European Countries with Spain Schengen Visa Assistance",
    overview: "Arizona offers comprehensive Spain & Schengen visa application filing, BLS appointment booking, travel insurance certificates, and financial document structuring.",
    requirements: [
      "Passport with at least 2 blank pages (valid 3+ months past travel date)",
      "Two Schengen-compliant biometric photos (35x45mm)",
      "6-Month bank statement with official bank stamp",
      "Employment verification letter / No Objection Certificate (NOC)",
      "Round-trip flight booking & verified hotel reservations",
      "Schengen Travel Health Insurance covering minimum €30,000",
    ],
    processSteps: [
      { step: "01", title: "Consultation & Document Audit", desc: "We review your financial profile and prepare a custom checklist." },
      { step: "02", title: "BLS Appointment Slot", desc: "We secure your biometrics appointment date and time." },
      { step: "03", title: "File Submission & Biometrics", desc: "Attend appointment with pre-organized document dossier." },
      { step: "04", title: "Passport Stamping & Delivery", desc: "Receive your stamped passport delivered safely." },
    ],
    included: ["BLS Slot Booking", "€30,000 Travel Insurance", "Cover Letter & Day-by-Day Itinerary"],
  },
  {
    slug: "thailand",
    name: "Thailand Tourist Visa",
    country: "Thailand",
    flag: "🇹🇭",
    region: "asia",
    regionName: "Southeast Asia",
    type: "Single Entry Tourist (TR) & eVisa",
    time: "3 - 5 Working Days",
    entryType: "Single Entry (60 Days extendable)",
    validity: "3 Months from Issue",
    heroImage: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=700&q=80&auto=format&fit=crop",
    tagline: "Fast & Hassle-Free Thai Visa for Bangkok, Phuket, and Pattaya",
    overview: "Arizona manages your online Thai eVisa filing with accurate sponsor declarations, hotel vouchers, and fast turnaround approvals.",
    requirements: [
      "Valid passport with 6 months validity",
      "Digital passport photograph",
      "Flight reservation into Thailand and outbound ticket",
      "Proof of accommodation / hotel booking",
      "Proof of financial funds (recent bank statement)",
    ],
    processSteps: [
      { step: "01", title: "Send Requirements", desc: "Provide scanned passport copy and photograph." },
      { step: "02", title: "Online Embassy Portal Filing", desc: "Our team pays fees and files directly on the Royal Thai Visa portal." },
      { step: "03", title: "Instant Visa PDF", desc: "Approved electronic sticker PDF sent directly to WhatsApp." },
    ],
    included: ["Online Portal Submission", "Hotel Verification Voucher", "Flight Ticket Itinerary"],
  },
  {
    slug: "switzerland",
    name: "Switzerland Schengen Visa",
    country: "Switzerland",
    flag: "🇨🇭",
    region: "europe",
    regionName: "Europe",
    type: "Tourist, Family Visit & Business",
    time: "15 - 20 Working Days",
    entryType: "Single / Multi Entry",
    validity: "Up to 90 Days",
    heroImage: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=700&q=80&auto=format&fit=crop",
    tagline: "Experience the Swiss Alps & Geneva with Complete Visa Preparation",
    overview: "Professional VFS appointment scheduling, Swiss travel insurance, and complete file preparation for tourism, business conferences, and alpine holidays.",
    requirements: [
      "Passport with 6+ months validity",
      "Swiss-standard biometric photos",
      "Bank statement of last 6 months",
      "Salary slips & NOC from employer",
      "Confirmed Swiss hotel bookings & flight itinerary",
      "Schengen insurance with minimum €30,000 coverage",
    ],
    processSteps: [
      { step: "01", title: "File Organization", desc: "Complete form filling and preparation of supporting documents." },
      { step: "02", title: "VFS Global Appointment", desc: "Schedule biometrics submission at the nearest center." },
      { step: "03", title: "Embassy Clearance", desc: "Track progress until approved visa is ready for collection." },
    ],
    included: ["VFS Booking", "Travel Health Insurance", "Hotel & Route Plan Dossier"],
  },
  {
    slug: "bahrain",
    name: "Kingdom of Bahrain Visa & Work Permits",
    country: "Kingdom of Bahrain",
    flag: "🇧🇭",
    region: "gcc",
    regionName: "GCC & Middle East",
    type: "Tourist eVisa, Business Visit & LMRA Investor Visa",
    time: "24 Hours - 4 Business Days",
    entryType: "Single & Multiple Entry (2 Weeks to 2 Years)",
    validity: "14 Days / 1 Month / 1 Year / 2 Years",
    heroImage: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=700&q=80&auto=format&fit=crop",
    tagline: "Official Bahrain eVisa, Multiple-Entry Tourist, and LMRA Work Permits",
    overview: "Direct government clearance through Bahrain MOIC & NPRA for tourist eVisas, investor visas, family visit visas, and permanent work permit residency.",
    requirements: [
      "Clear passport copy with minimum 6 months validity",
      "Passport-sized digital photograph",
      "Bahrain hotel booking or resident sponsor details",
      "For Investor Visa: Commercial Registration (CR) and CPR copies",
    ],
    processSteps: [
      { step: "01", title: "Document Upload", desc: "Send passport copy through WhatsApp or online form." },
      { step: "02", title: "Direct NPRA / LMRA Filing", desc: "Government fee payment and expedited processing." },
      { step: "03", title: "Visa Issuance", desc: "Approved Bahrain visa delivered with QR verification." },
    ],
    included: ["Direct NPRA Government Portal Submission", "Extension Advisory", "Airport Clearance Support"],
  },
  {
    slug: "uk",
    name: "United Kingdom (UK) Visitor Visa",
    country: "United Kingdom",
    flag: "🇬🇧",
    region: "europe",
    regionName: "Europe",
    type: "Standard Visitor Visa (6 Months / 2 Yrs / 5 Yrs)",
    time: "3 - 4 Weeks (Priority Available)",
    entryType: "Multiple Entry",
    validity: "6 Months up to 10 Years",
    heroImage: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=700&q=80&auto=format&fit=crop",
    tagline: "Visit London, Edinburgh, and Manchester with Dedicated UK Visa Experts",
    overview: "We guide you through the UK.GOV application portal, financial source documentation, VFS biometrics appointment, and priority processing options.",
    requirements: [
      "Original Passport valid for duration of stay",
      "Bank statements of last 6 months with clear income sources",
      "Employment proof, salary certificate & tax records",
      "Proof of assets, ties to home country, and travel history",
      "Detailed itinerary and UK accommodation details",
    ],
    processSteps: [
      { step: "01", title: "UK.GOV Portal Submission", desc: "Flawless form completion and fee processing." },
      { step: "02", title: "Document Upload & Biometrics", desc: "Upload categorized proofs and attend VFS biometrics." },
      { step: "03", title: "Decision & Stamped Passport", desc: "UKVI decision notification and passport delivery." },
    ],
    included: ["Complete Online Application Support", "Financial Dossier Formatting", "VFS Appointment Scheduling"],
  },
  {
    slug: "usa",
    name: "United States (USA) B1/B2 Visitor Visa",
    country: "United States (USA)",
    flag: "🇺🇸",
    region: "americas",
    regionName: "North America",
    type: "B1/B2 Tourism & Business Visa",
    time: "Based on US Embassy Interview Appointment",
    entryType: "5 or 10-Year Multiple Entry",
    validity: "Up to 10 Years (180 days per stay)",
    heroImage: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=700&q=80&auto=format&fit=crop",
    tagline: "Expert DS-160 Form Filing & Interview Consultation for USA B1/B2 Visas",
    overview: "Our experienced visa consultants review your background, accurately fill your DS-160, schedule MRV fee payments, book earlier appointment slots, and conduct one-on-one interview preparation.",
    requirements: [
      "Valid passport with 6 months validity beyond intended stay",
      "Digital US Visa photograph (2x2 inches / 51x51mm)",
      "Previous US visas (if applicable)",
      "Proof of employment, business ownership, and financial assets",
      "Purpose of travel and ties to home country",
    ],
    processSteps: [
      { step: "01", title: "DS-160 Form Filling", desc: "Meticulous completion of all sections to eliminate rejection risk." },
      { step: "02", title: "Fee Payment & Slot Booking", desc: "MRV fee processing and securing earliest available interview date." },
      { step: "03", title: "Interview Prep Session", desc: "Mock questions and answers with senior visa advisors." },
      { step: "04", title: "Embassy Interview & Approval", desc: "Attend interview and receive 10-year multi-entry visa." },
    ],
    included: ["Full DS-160 Submission", "Appointment Slot Management", "One-on-One Interview Coaching"],
  },
  {
    slug: "canada",
    name: "Canada Visitor Visa & eTA",
    country: "Canada",
    flag: "🇨🇦",
    region: "americas",
    regionName: "North America",
    type: "Temporary Resident Visa (TRV) / eTA",
    time: "3 - 6 Weeks",
    entryType: "Multiple Entry (Up to Passport Expiry)",
    validity: "Up to 10 Years",
    heroImage: "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=700&q=80&auto=format&fit=crop",
    tagline: "Travel to Toronto, Vancouver, and Montreal with Canada TRV Assistance",
    overview: "Complete IRCC portal application management, family sponsorship guidance, financial structuring, and VFS biometrics coordination for Canadian visitor visas.",
    requirements: [
      "Valid passport for entire duration",
      "Digital biometric photograph according to IRCC specs",
      "Proof of financial solvency (6 months bank statement)",
      "Employment letter / business ownership documents",
      "Family ties and purpose of visit explanation",
    ],
    processSteps: [
      { step: "01", title: "IRCC Portal Application", desc: "Complete account setup and digital file upload." },
      { step: "02", title: "Biometrics Instruction Letter (BIL)", desc: "Schedule biometrics at VFS Canada." },
      { step: "03", title: "Passport Request Letter (PPR)", desc: "Passport submission for visa foil stamping." },
    ],
    included: ["IRCC Portal Filing", "Purpose of Travel Statement", "Biometrics Appointment Booking"],
  },
  {
    slug: "australia",
    name: "Australia Visitor Visa (Subclass 600)",
    country: "Australia",
    flag: "🇦🇺",
    region: "americas",
    regionName: "Oceania",
    type: "Subclass 600 Tourist & Business Stream",
    time: "2 - 4 Weeks",
    entryType: "Single & Multiple Entry (3, 6, or 12 Months)",
    validity: "Up to 1 Year",
    heroImage: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=700&q=80&auto=format&fit=crop",
    tagline: "Explore Sydney, Melbourne, and Gold Coast with Australia Subclass 600",
    overview: "100% digital ImmiAccount application handling with genuine temporary entrant (GTE) statement preparation, financial audits, and electronic visa delivery.",
    requirements: [
      "Color scan of passport bio page and previous travel stamps",
      "National ID / Residence proof",
      "Proof of funds (bank statements, investments)",
      "Employment confirmation letter with approved leave",
      "Travel itinerary and hotel reservations",
    ],
    processSteps: [
      { step: "01", title: "ImmiAccount Filing", desc: "Upload verified documents on Australian Department of Home Affairs." },
      { step: "02", title: "Biometrics & Health (if requested)", desc: "Coordinate appointment if required for your nationality." },
      { step: "03", title: "eVisa Grant Notification", desc: "Receive official electronic visa grant notice." },
    ],
    included: ["ImmiAccount Direct Submission", "GTE Statement Drafting", "24/7 Status Updates"],
  },
  {
    slug: "france",
    name: "France (Schengen) Visa",
    country: "France",
    flag: "🇫🇷",
    region: "europe",
    regionName: "Europe",
    type: "Short-Stay Schengen Visa (Tourism & Business)",
    time: "15 - 20 Working Days",
    entryType: "Single / Multi Entry",
    validity: "Up to 90 Days",
    heroImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=700&q=80&auto=format&fit=crop",
    tagline: "Visit Paris, Nice, and the French Riviera with Verified Visa Clearance",
    overview: "France-Visas official portal filing, TLScontact / VFS appointment securing, hotel bookings, and travel insurance for your French holiday.",
    requirements: [
      "Passport valid 3 months beyond intended departure",
      "2 France Schengen standard photographs",
      "6-Month active bank statements",
      "No Objection Certificate (NOC) from employer",
      "Flight itinerary & confirmed accommodation",
      "Schengen insurance coverage (€30,000)",
    ],
    processSteps: [
      { step: "01", title: "France-Visas Online Registration", desc: "Generate official registration receipt." },
      { step: "02", title: "TLS / VFS Appointment", desc: "Biometrics and physical dossier submission." },
      { step: "03", title: "Passport Stamping", desc: "Collect stamped passport with Schengen visa." },
    ],
    included: ["France-Visas Portal Registration", "Travel Health Insurance", "Hotel Reservation Dossier"],
  },
  {
    slug: "azerbaijan",
    name: "Azerbaijan ASAN Tourist eVisa",
    country: "Azerbaijan",
    flag: "🇦🇿",
    region: "asia",
    regionName: "Eurasia",
    type: "ASAN Tourist eVisa (Standard & Urgent)",
    time: "24 - 72 Hours (Express 3 Hours Available)",
    entryType: "Single Entry (30 Days)",
    validity: "90 Days from Issue",
    heroImage: "https://images.unsplash.com/photo-1589802829985-817e51171b92?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1589802829985-817e51171b92?w=700&q=80&auto=format&fit=crop",
    tagline: "Visit Baku, Gabala, and Shahdag with Instant Azerbaijan eVisas",
    overview: "Fastest turnaround eVisa processing directly via the official ASAN Viza system with flight ticketing, Baku hotel bookings, and airport pickup packages.",
    requirements: [
      "Clear passport copy with minimum 6 months validity",
      "Email address and WhatsApp number for PDF delivery",
    ],
    processSteps: [
      { step: "01", title: "Send Passport Scan", desc: "Submit via WhatsApp or our online portal." },
      { step: "02", title: "ASAN Official Processing", desc: "Instant fee payment and government submission." },
      { step: "03", title: "Receive eVisa PDF", desc: "Get approved eVisa sent straight to your device." },
    ],
    included: ["Direct ASAN Fee Submission", "Urgent 3-Hour Processing Available", "Baku Tour Packages"],
  },
  {
    slug: "south-africa",
    name: "South Africa Visitor Visa",
    country: "South Africa",
    flag: "🇿🇦",
    region: "africa",
    regionName: "Africa",
    type: "Tourist & Visitor Visa",
    time: "10 - 15 Business Days",
    entryType: "Single & Multiple Entry",
    validity: "Up to 90 Days",
    heroImage: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=1600&q=85&auto=format&fit=crop",
    cardImage: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=700&q=80&auto=format&fit=crop",
    tagline: "Explore Cape Town, Kruger National Park, and Johannesburg",
    overview: "Complete South African embassy file preparation, safari itinerary structuring, flight bookings, and verified hotel vouchers.",
    requirements: [
      "Original passport with 2 blank pages (valid 30+ days post trip)",
      "2 Passport photos (35x45mm)",
      "3-Month bank statement with bank stamp",
      "Employment letter / business registration",
      "Flight reservation and day-to-day itinerary",
    ],
    processSteps: [
      { step: "01", title: "Document Organization", desc: "Complete form filling and safari itinerary creation." },
      { step: "02", title: "VFS / Embassy Filing", desc: "Submit application with all verified attachments." },
      { step: "03", title: "Visa Stamping", desc: "Receive your approved South Africa visa foil." },
    ],
    included: ["Application Filing Support", "Hotel & Flight Booking", "Safari Itinerary Preparation"],
  },
];

export interface ServiceItemDetail {
  slug: string;
  name: string;
  desc: string;
  tag: string;
  image: string;
  price: string;
  gallery: string[];
  options: { name: string; price: string; period?: string; capacity?: string; badge?: string; desc?: string }[];
  about: string;
}

export interface BusinessDivision {
  slug: string;
  id: string;
  title: string;
  subtitle: string;
  category: string;
  tagline: string;
  heroImage: string;
  overview: string;
  features: { title: string; desc: string; iconName: string }[];
  servicesList: ServiceItemDetail[];
  faqs: { q: string; a: string }[];
}

export const businessDivisionsData: BusinessDivision[] = [
  {
    slug: "travel-tours",
    id: "travel",
    title: "Travel & Tours",
    subtitle: "Global Flight Ticketing, Visas & Custom Holiday Packages",
    category: "Travel & Tourism Division",
    tagline: "Seamless Global Journeys Crafted for Discerning Travelers",
    heroImage: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=85&auto=format&fit=crop",
    overview: "Arizona Travel & Tours is your trusted partner for domestic and international flight reservations, worldwide visa assistance, luxury honeymoon getaways, 5-star hotel accommodations, desert safari excursions, and comprehensive Umrah packages with dedicated 24/7 client care.",
    features: [
      { title: "Instant Flight Ticketing", desc: "Direct airline inventory access across major global carriers with flexible rebooking.", iconName: "Plane" },
      { title: "Worldwide Visa Processing", desc: "Expert facilitation for Schengen, UK, USA, Canada, Bahrain, and Asian visas with high approvals.", iconName: "Globe" },
      { title: "Luxury Resorts & Stays", desc: "Exclusive corporate and VIP rates at premium 5-star hotels, villas, and beachfront resorts.", iconName: "Building2" },
      { title: "Umrah & Ziyarat Care", desc: "Complete spiritual packages including ground logistics, verified hotels, and visa support.", iconName: "ShieldCheck" },
    ],
    servicesList: [
      {
        slug: "flight-tickets",
        name: "Flight Ticket Booking",
        desc: "Instant reservations across major global airlines with flexible rebooking assistance.",
        tag: "Instant Confirmation",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80&auto=format&fit=crop",
        price: "Best Market Rates",
        gallery: [
          "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Economy Class Reservation", price: "Starting from PKR 45,000", period: "per ticket", capacity: "1 - 9 Passengers", badge: "Most Popular", desc: "Standard baggage allowance, meal options, and free web check-in." },
          { name: "Business Class Luxury", price: "Starting from PKR 180,000", period: "per ticket", capacity: "VIP Priority", badge: "Executive", desc: "Priority check-in, lounge access, flat-bed seating, and gourmet dining." },
          { name: "First Class Suite", price: "Custom Quote", period: "per route", capacity: "Ultra VIP", badge: "Exclusive", desc: "Private enclosed suites, chauffeur airport transfer, and personal concierge." },
          { name: "Group & Corporate Booking", price: "Discounted Group Fare", period: "10+ passengers", capacity: "Delegations", badge: "Corporate", desc: "Flexible name changes, dedicated corporate travel manager, and invoice terms." },
        ],
        about: "Arizona Flight Booking Desk connects directly with world-class airlines across the GCC, Europe, Americas, and Asia. Enjoy real-time seat selection, instant electronic e-ticket confirmation, 24/7 date changes, and emergency rescheduling.",
      },
      {
        slug: "worldwide-visas",
        name: "Worldwide Visa Services",
        desc: "Fast tourist, business, transit, and family visa processing with high approval success.",
        tag: "Worldwide Visas",
        image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80&auto=format&fit=crop",
        price: "Certified Filing",
        gallery: [
          "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Electronic Tourist eVisa", price: "Starting from PKR 18,500", period: "per applicant", capacity: "Individual / Family", badge: "Fast Track", desc: "3-5 day issuance for Bahrain, Malaysia, Thailand, UAE, and Azerbaijan." },
          { name: "Schengen & European Visa", price: "Consultation & Dossier", period: "per dossier", capacity: "Schengen Area", badge: "High Success", desc: "Appointment booking (BLS/VFS), travel insurance, hotel bookings, and audit." },
          { name: "USA / UK / Canada Visa", price: "Full Application Package", period: "per submission", capacity: "Multiple Entry", badge: "Tier 1", desc: "DS-160 filing, appointment expedite assistance, and mock interview prep." },
          { name: "GCC Investor / Business Visa", price: "Direct Clearance", period: "per company", capacity: "Business Owners", badge: "Institutional", desc: "Bahrain LMRA investor visas, Saudi business visas, and executive entry." },
        ],
        about: "Our visa specialists guide applicants step-by-step through government requirements, eligibility criteria, certified translations, and official embassy submission with industry-leading approval ratios.",
      },
      {
        slug: "hotels-resorts",
        name: "5-Star Resorts & Hotels",
        desc: "Exclusive negotiated rates at top luxury hotels, resorts, and serviced suites.",
        tag: "5-Star Stays",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 7,040",
        gallery: [
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Standard Deluxe Room", price: "PKR 7,040", period: "per night", capacity: "2 Guests", badge: "Breakfast Included", desc: "King bed, complimentary high-speed Wi-Fi, city/sea view, and luxury bath amenities." },
          { name: "Executive Suite", price: "PKR 14,500", period: "per night", capacity: "2 - 3 Guests", badge: "Lounge Access", desc: "Separate living salon, complimentary airport shuttle, breakfast, and evening drinks." },
          { name: "Family Villa / Quad Room", price: "PKR 28,900", period: "per night", capacity: "4 - 5 Guests", badge: "Private Pool", desc: "Spacious multi-bedroom accommodation with private balcony, kitchenette, and room service." },
          { name: "Presidential Royal Suite", price: "PKR 65,000", period: "per night", capacity: "VIP Delegation", badge: "Ultra Luxury", desc: "Panoramic penthouse view, private butler service, jacuzzi, and VIP boardroom." },
        ],
        about: "Arizona coordinates luxury accommodation worldwide. From beachfront private pool villas in Bali to landmark city-center 5-star suites in Dubai, London, and Manama, enjoy guaranteed best rates and room upgrades.",
      },
      {
        slug: "holiday-escapes",
        name: "Holiday & Exotic Escapes",
        desc: "Customized holiday itineraries crafted for families, couples, and luxury excursions.",
        tag: "All-Inclusive",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 95,000",
        gallery: [
          "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Tropical Beach Getaway (5D/4N)", price: "PKR 95,000", period: "per person", capacity: "Couples / Friends", badge: "Popular", desc: "Includes flights, 4-star beach resort, island hopping tours, and breakfast." },
          { name: "European Highlights Tour (8D/7N)", price: "PKR 260,000", period: "per person", capacity: "Groups / Solo", badge: "Guided Tour", desc: "Multi-country train transfers, 4-star stays, guided excursions in France & Switzerland." },
          { name: "Luxury Honeymoon Special (6D/5N)", price: "PKR 320,000", period: "per couple", capacity: "2 Persons", badge: "Romantic VIP", desc: "Water villa stay, candlelit dinner on the beach, couple spa, and private speedboat." },
          { name: "Family Holiday Extravaganza", price: "PKR 390,000", period: "family package", capacity: "4 Persons", badge: "All-Inclusive", desc: "Theme park passes, family suite accommodation, private SUV transfers, and meals." },
        ],
        about: "Experience handcrafted vacations designed by expert travel architects. Every package combines flights, luxury stays, private sightseeing, visa support, and 24/7 dedicated trip coordination.",
      },
      {
        slug: "umrah-spiritual",
        name: "Umrah & Spiritual Journeys",
        desc: "Comprehensive Umrah and Ziyarat packages with VIP ground transfers and hotel guidance.",
        tag: "Spiritual Care",
        image: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 135,000",
        gallery: [
          "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1565552684305-7e780447385a?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Economy Umrah Package (10 Days)", price: "PKR 135,000", period: "per pilgrim", capacity: "Quad Sharing", badge: "Budget Friendly", desc: "Umrah visa, return flights, 3-star hotel within walking distance, and Ziyarat." },
          { name: "Executive 4-Star Umrah (14 Days)", price: "PKR 210,000", period: "per pilgrim", capacity: "Double / Triple", badge: "Recommended", desc: "4-star hotels in Makkah & Madinah (Clock Tower proximity), GMC transfers." },
          { name: "VIP 5-Star Front Row Stay (10 Days)", price: "PKR 380,000", period: "per pilgrim", capacity: "Private Room", badge: "Haram View", desc: "Direct Haram view 5-star suite, private luxury SUV, VIP airport meet & assist." },
        ],
        about: "Our dedicated religious travel department ensures peace of mind for you and your family with verified hotel bookings near the Holy Mosques in Makkah and Madinah, ground transport, and complete visa processing.",
      },
      {
        slug: "desert-safari",
        name: "Desert Safaris & Adventures",
        desc: "Breathtaking dune bashing, luxury Arabian desert camps, and private camel treks.",
        tag: "VIP Itineraries",
        image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 12,000",
        gallery: [
          "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Evening Desert Safari & BBQ", price: "PKR 12,000", period: "per person", capacity: "Sharing SUV", badge: "Best Seller", desc: "4x4 dune bashing, camel riding, sandboarding, BBQ dinner, and live shows." },
          { name: "VIP Private Desert Camp", price: "PKR 45,000", period: "private group", capacity: "Up to 6 Guests", badge: "Private", desc: "Exclusive 4x4 vehicle, private dining gazebo, premium barbecue, and stargazing." },
          { name: "Overnight Desert Glamping", price: "PKR 35,000", period: "per tent", capacity: "2 Guests", badge: "Luxury Camp", desc: "Air-conditioned luxury tent, sunrise camel trek, traditional breakfast, and campfire." },
        ],
        about: "Discover authentic Arabian desert adventures with certified desert drivers, safety-equipped 4x4 Land Cruisers, traditional Arabian hospitality, and unforgettable scenic sunsets.",
      },
    ],
    faqs: [
      { q: "How quickly can you issue flight tickets?", a: "We provide instant ticket issuance and confirmation within minutes via WhatsApp or email." },
      { q: "Do you handle visa appointments?", a: "Yes, we handle complete appointment scheduling for VFS, BLS, TLS, and US Embassy interview slots." },
      { q: "Can I customize my holiday package?", a: "Absolutely! Our travel advisors build bespoke itineraries tailored to your budget and preferences." },
    ],
  },
  {
    slug: "rent-a-car",
    id: "cars",
    title: "Rent A Car",
    subtitle: "Daily, Weekly & Monthly Self-Drive & Chauffeur Fleet",
    category: "Mobility & Chauffeur Division",
    tagline: "Reliable, Premium & Versatile Mobility Wherever You Go",
    heroImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1600&q=85&auto=format&fit=crop",
    overview: "Arizona Rent A Car delivers high-quality fleet solutions tailored for business executives, families, and visiting travelers. Choose from economical self-drive sedans, luxury SUVs, and professional uniformed chauffeur services with 24/7 roadside assistance.",
    features: [
      { title: "Diverse Fleet Selection", desc: "From fuel-efficient economy sedans to luxury Mercedes-Benz, Range Rover, and sports convertibles.", iconName: "Car" },
      { title: "24/7 Airport Transfers", desc: "Punctual terminal meet & greet, real-time flight tracking, and door-to-door convenience.", iconName: "Clock" },
      { title: "VIP Chauffeur Services", desc: "Licensed, professional, multilingual drivers for corporate events and private itineraries.", iconName: "Users" },
      { title: "Transparent & Insured", desc: "Comprehensive insurance coverage, zero hidden fees, and hassle-free quick verification.", iconName: "ShieldCheck" },
    ],
    servicesList: [
      {
        slug: "daily-rentals",
        name: "Daily & Weekly Rentals",
        desc: "Flexible self-drive fleet ranging from economy sedans to sports convertibles.",
        tag: "Flexible Plans",
        image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 4,500 / day",
        gallery: [
          "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Economy Sedan (Toyota Yaris / Corolla)", price: "PKR 4,500", period: "per day", capacity: "4 Passengers", badge: "Fuel Efficient", desc: "Automatic transmission, Bluetooth, full AC, comprehensive insurance." },
          { name: "Standard Midsize (Honda Civic / Sonata)", price: "PKR 7,500", period: "per day", capacity: "5 Passengers", badge: "Popular", desc: "Cruise control, rear camera, premium sound system, unlimited city miles." },
          { name: "Executive Luxury (Mercedes C-Class / BMW)", price: "PKR 22,000", period: "per day", capacity: "VIP Comfort", badge: "Premium", desc: "Leather interior, ambient lighting, high horsepower, luxury prestige." },
        ],
        about: "Choose from our pristine, late-model vehicle fleet. We deliver and collect directly to your home, office, or airport terminal with zero paperwork hassle.",
      },
      {
        slug: "airport-transfers",
        name: "Airport Meet & Greet",
        desc: "Punctual terminal airport transfers with real-time flight tracking and luggage care.",
        tag: "24/7 Transfers",
        image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 5,000",
        gallery: [
          "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1563720223185-11003d516935?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Sedan Airport Drop-off", price: "PKR 5,000", period: "one-way", capacity: "3 Passengers + 2 Bags", badge: "Standard", desc: "Punctual driver, direct highway route, air-conditioned comfortable ride." },
          { name: "SUV Airport Arrival Pickup", price: "PKR 8,500", period: "one-way", capacity: "5 Passengers + 4 Bags", badge: "Family SUV", desc: "Meet & greet with nameboard at arrivals hall, flight delay monitoring." },
          { name: "VIP Chauffeur Transfer (Mercedes S-Class)", price: "PKR 25,000", period: "one-way", capacity: "VIP Protocol", badge: "Executive", desc: "Uniformed driver, complimentary bottled water, Wi-Fi on board." },
        ],
        about: "Never stress about missing a flight or waiting for a taxi. Our airport transfer service features live flight tracking, complimentary waiting time, and courteous chauffeurs.",
      },
      {
        slug: "vip-chauffeur",
        name: "VIP Chauffeur Services",
        desc: "Professional uniformed private drivers for corporate executives and VIP delegations.",
        tag: "VIP Protocol",
        image: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 15,000 / day",
        gallery: [
          "https://images.unsplash.com/photo-1563720223185-11003d516935?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Half-Day Chauffeur (5 Hours)", price: "PKR 9,500", period: "5 hours", capacity: "Executive Car", badge: "Business", desc: "Dedicated driver for local meetings and corporate transport." },
          { name: "Full-Day Chauffeur (10 Hours)", price: "PKR 16,000", period: "10 hours", capacity: "Luxury Sedan", badge: "Full Day", desc: "Flexible itinerary, fuel included for city limits, professional driver." },
        ],
        about: "Travel in comfort and style with our background-checked, multilingual executive chauffeurs trained in corporate etiquette and VIP discretion.",
      },
      {
        slug: "luxury-suvs",
        name: "Luxury SUVs & 4x4",
        desc: "Range Rover, Mercedes-Benz G-Wagon, and premium all-terrain family SUVs.",
        tag: "Premium Fleet",
        image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 25,000 / day",
        gallery: [
          "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Toyota Land Cruiser Prado", price: "PKR 25,000", period: "per day", capacity: "7 Passengers", badge: "Robust", desc: "4x4 capability, 7 leather seats, supreme comfort for long road trips." },
          { name: "Range Rover Vogue", price: "PKR 55,000", period: "per day", capacity: "5 Passengers", badge: "Prestige", desc: "Panoramic sunroof, meridian sound, adaptive air suspension." },
        ],
        about: "Experience power and prestige with our luxury 4x4 and SUV line. Perfect for high-level business delegations, VIP family road trips, and scenic tours.",
      },
      {
        slug: "wedding-events",
        name: "Wedding & Special Events",
        desc: "Exotic sedans and luxury limousines decorated for weddings and corporate events.",
        tag: "Special Events",
        image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 30,000",
        gallery: [
          "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Bridal Mercedes S-Class", price: "PKR 35,000", period: "event package", capacity: "Bridal Couple", badge: "Decorated", desc: "Includes flower decoration, uniformed driver, and red carpet protocol." },
          { name: "Groom Convoy SUV Package", price: "PKR 65,000", period: "3 SUVs", capacity: "Family Convoy", badge: "Convoy", desc: "3 matching luxury SUVs with professional drivers for wedding convoy." },
        ],
        about: "Make your special day unforgettable with our fleet of pristine luxury bridal cars and corporate event transport logistics.",
      },
      {
        slug: "corporate-lease",
        name: "Corporate Long-Term Lease",
        desc: "Cost-effective business fleet leasing with complete insurance and routine maintenance.",
        tag: "Corporate Fleet",
        image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&q=80&auto=format&fit=crop",
        price: "Monthly Contract Rates",
        gallery: [
          "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Monthly Sedan Lease", price: "PKR 85,000", period: "per month", capacity: "Corporate Staff", badge: "All-Inclusive", desc: "Comprehensive insurance, scheduled maintenance, and replacement vehicle guarantee." },
          { name: "Monthly SUV Executive Lease", price: "PKR 180,000", period: "per month", capacity: "Directors / C-Level", badge: "Turnkey", desc: "Full service corporate fleet with tax invoices and 24/7 breakdown support." },
        ],
        about: "Optimize your corporate mobility without capital expenditure. We provide tailored monthly and annual fleet leasing with complete maintenance.",
      },
    ],
    faqs: [
      { q: "What documents are required to rent a car?", a: "Valid Driving License (or International Driving Permit for tourists) and Passport / ID copy." },
      { q: "Is insurance included in rental rates?", a: "Yes, standard comprehensive insurance is included across our fleet with optional full-coverage upgrades." },
      { q: "Can the car be delivered to my hotel or airport?", a: "Yes, we provide doorstep vehicle delivery and collection anywhere in the city and airport terminals." },
    ],
  },
  {
    slug: "business-bahrain",
    id: "bahrain",
    title: "Business in Bahrain",
    subtitle: "Company Formation, 100% Foreign Ownership & Turnkey Offices",
    category: "Corporate Formation Division",
    tagline: "Build Your Business. Own Your Future in Bahrain.",
    heroImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&q=85&auto=format&fit=crop",
    overview: "Arizona provides end-to-end corporate setup in the Kingdom of Bahrain. From establishing 100% foreign-owned WLL companies and Commercial Registrations (CR) to commercial offices with EWA, corporate banking, LMRA investor visas, and NBR VAT compliance.",
    features: [
      { title: "100% Foreign Ownership", desc: "Full investor rights under Bahrain MOIC regulations for WLL, SPC, and foreign branch setups.", iconName: "Building2" },
      { title: "Turnkey Office & EWA", desc: "Fully compliant commercial workspace leasing with electricity and water connections.", iconName: "Briefcase" },
      { title: "Corporate Banking Setup", desc: "Seamless corporate business account opening support with top Bahrain & global banks.", iconName: "Landmark" },
      { title: "LMRA Investor Visas", desc: "Work permit ceiling allocation, investor residency, and employee visa clearance.", iconName: "Users" },
    ],
    servicesList: [
      {
        slug: "foreign-ownership-cr",
        name: "100% Foreign Ownership Setup",
        desc: "Commercial Registration (CR), Single Person Company (SPC), and WLL setup.",
        tag: "Gov Approved",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80&auto=format&fit=crop",
        price: "Starting from BHD 350",
        gallery: [
          "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "With Limited Liability (WLL)", price: "BHD 450", period: "one-time setup", capacity: "1 - 50 Partners", badge: "100% Ownership", desc: "Full foreign ownership, no local sponsor required, MOIC official registration." },
          { name: "Single Person Company (SPC)", price: "BHD 350", period: "one-time setup", capacity: "Sole Proprietor", badge: "Fast Approval", desc: "Ideal for individual entrepreneurs, rapid issuance, official company stamp." },
          { name: "Foreign Company Branch", price: "BHD 650", period: "one-time setup", capacity: "Global Firms", badge: "International", desc: "Direct legal branch of international parent company in Bahrain." },
        ],
        about: "Bahrain is the most cost-effective business gateway to Saudi Arabia and the GCC. We handle complete commercial activity selection, name reservation, memorandum of association (MOA) notarization, and final CR certificate issuance.",
      },
      {
        slug: "turnkey-office-ewa",
        name: "Turnkey Office with EWA",
        desc: "Fully compliant commercial workspaces with electricity and water connections.",
        tag: "Turnkey Office",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80&auto=format&fit=crop",
        price: "Starting from BHD 120 / month",
        gallery: [
          "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Business Incubator Address", price: "BHD 75", period: "per month", capacity: "Startups & Services", badge: "Cost Saver", desc: "MOIC-approved commercial address with municipality approval." },
          { name: "Furnished Executive Office", price: "BHD 180", period: "per month", capacity: "3 - 5 Workstations", badge: "EWA Included", desc: "Includes high-speed internet, meeting room access, receptionist, and EWA." },
        ],
        about: "Secure an official MOIC-approved office address in prime business districts (Diplomatic Area, Seef, Manama) equipped with active EWA electricity connections and municipality compliance.",
      },
      {
        slug: "corporate-bank-account",
        name: "Corporate Bank Account",
        desc: "Seamless business bank account opening support with top Bahrain & global banks.",
        tag: "Banking Support",
        image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&q=80&auto=format&fit=crop",
        price: "Guaranteed Submission",
        gallery: [
          "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Commercial Corporate Account", price: "Assistance Package", period: "multi-currency", capacity: "WLL / SPC", badge: "Top Banks", desc: "Assistance with NBB, BBK, Al Salam Bank, AUB, and Standard Chartered." },
        ],
        about: "We structure your business profile, proof of business, and documentation to pass compliance checks and open corporate multi-currency checking accounts.",
      },
      {
        slug: "lmra-work-permits",
        name: "LMRA Work Permits & Visas",
        desc: "Labour Market Regulatory Authority registration, ceiling setup, and investor visas.",
        tag: "LMRA & Visas",
        image: "https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&q=80&auto=format&fit=crop",
        price: "Starting from BHD 250",
        gallery: [
          "https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "2-Year Investor Residency Visa", price: "BHD 350", period: "2-year renewable", capacity: "Business Owners", badge: "Residency", desc: "Includes Bahrain CPR identity card, health insurance, and family sponsorship rights." },
          { name: "LMRA Work Permit Ceiling", price: "BHD 150", period: "per allocation", capacity: "Employees", badge: "Work Permits", desc: "Audit and approval for hiring foreign staff and issuing work permits." },
        ],
        about: "Complete Labour Market Regulatory Authority (LMRA) enrollment, biometric scheduling, medical checkups, and Bahrain CPR cards for partners, executives, and employees.",
      },
      {
        slug: "cr-amendments",
        name: "CR Amendments & Renewals",
        desc: "Adding business activities, address amendments, and annual MOIC license renewals.",
        tag: "MOIC Certified",
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80&auto=format&fit=crop",
        price: "Starting from BHD 100",
        gallery: [
          "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Add/Remove Commercial Activities", price: "BHD 120", period: "per amendment", capacity: "CR Updates", badge: "MOIC Sijilat", desc: "Updating business scope with relevant ministry approvals." },
          { name: "Annual CR & Municipality Renewal", price: "BHD 95", period: "annual", capacity: "Compliance", badge: "Fast Renewal", desc: "Complete renewal filing with zero penalty guarantees." },
        ],
        about: "Keep your commercial entity in full standing with prompt annual renewals, partner changes, capital increases, and activity amendments.",
      },
      {
        slug: "vat-tax-accounting",
        name: "VAT Registration & Tax",
        desc: "National Bureau for Revenue (NBR) VAT filing, monthly bookkeeping, and payroll.",
        tag: "VAT & Tax",
        image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80&auto=format&fit=crop",
        price: "Starting from BHD 50 / month",
        gallery: [
          "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "NBR VAT Registration Certificate", price: "BHD 100", period: "one-time", capacity: "Tax ID", badge: "NBR Compliant", desc: "Official VAT registration and issuance of VAT certificate." },
          { name: "Monthly Bookkeeping & VAT Returns", price: "BHD 60", period: "per month", capacity: "Quarterly Returns", badge: "Accounting", desc: "Complete financial statement preparation, VAT return submissions, and audit prep." },
        ],
        about: "Ensure full compliance with Bahrain tax regulations and statutory corporate financial reporting with our certified chartered accountants.",
      },
    ],
    faqs: [
      { q: "Can a foreigner own 100% of a company in Bahrain?", a: "Yes, under Bahrain law, foreign investors can own 100% of most commercial activities without a local sponsor." },
      { q: "How long does it take to register a CR?", a: "Typically 3 to 7 working days depending on the selected commercial activities and ministry approvals." },
      { q: "Do I get a residency visa after forming a company?", a: "Yes, company owners are entitled to an LMRA Investor Visa providing 2-year renewable Bahrain residency." },
    ],
  },
  {
    slug: "mobiles-tech",
    id: "mobiles",
    title: "Mobiles & Tech",
    subtitle: "Original Smartphones, Fast Chargers, Wearables & Audio",
    category: "Consumer Tech Division",
    tagline: "Authentic Flagship Gadgets & Accessories Delivered Same-Day",
    heroImage: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1600&q=85&auto=format&fit=crop",
    overview: "Arizona Mobiles & Tech provides 100% authentic sealed smartphones (Apple, Samsung, Google Pixel), certified high-speed GaN chargers, premium smartwatches, noise-cancelling wireless audio, and durable travel power accessories with express doorstep delivery.",
    features: [
      { title: "100% Sealed & Genuine", desc: "Factory-sealed original devices with manufacturer warranty and verification.", iconName: "ShieldCheck" },
      { title: "Express Doorstep Delivery", desc: "Same-day home, office, or hotel dispatch with real-time tracking.", iconName: "Clock" },
      { title: "Curated Tech Accessories", desc: "Certified fast chargers, durable braided cables, magnetic wireless power banks, and audio gear.", iconName: "Smartphone" },
      { title: "Direct WhatsApp Ordering", desc: "Order instantly through WhatsApp chat with dedicated support.", iconName: "ArrowUpRight" },
    ],
    servicesList: [
      {
        slug: "flagship-smartphones",
        name: "Flagship Smartphones",
        desc: "Brand-new, sealed iPhones, Samsung Galaxy, and Google Pixel flagships.",
        tag: "100% Genuine",
        image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 110,000",
        gallery: [
          "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1600&q=85&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Apple iPhone 16 / 15 Pro Max", price: "Market Best Price", period: "1 Year Apple Warranty", capacity: "128GB / 256GB / 512GB", badge: "Bestseller", desc: "Factory unlocked, sealed box, official warranty, all colors available." },
          { name: "Samsung Galaxy S24 Ultra", price: "Market Best Price", period: "Official Warranty", capacity: "256GB / 512GB", badge: "AI Flagship", desc: "Snapdragon 8 Gen 3, Titanium finish, S-Pen included, sealed box." },
        ],
        about: "Buy authentic flagship smartphones with confidence. All units are brand new, factory sealed, non-refurbished, and backed by manufacturer warranty.",
      },
      {
        slug: "fast-chargers",
        name: "Fast Chargers & GaN Cables",
        desc: "High-wattage rapid wall chargers, certified Type-C, and durable accessories.",
        tag: "Certified Safe",
        image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 3,200",
        gallery: [
          "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "65W GaN Dual-Port Fast Charger", price: "PKR 4,800", period: "unit", capacity: "USB-C + USB-A", badge: "Super Fast", desc: "Charges laptops, phones, and tablets with heat protection." },
          { name: "Braided 100W PD Type-C Cable (2M)", price: "PKR 2,200", period: "unit", capacity: "100W Power Delivery", badge: "Durable", desc: "Military-grade nylon braided wire, gold-plated connectors." },
        ],
        about: "High-performance GaN semiconductor chargers that deliver maximum speed while keeping your valuable devices cool and protected from surges.",
      },
      {
        slug: "smartwatches",
        name: "Smartwatches & Wearables",
        desc: "Apple Watch Series, Galaxy Watch, and premium fitness tracking wearables.",
        tag: "Smart Tech",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 24,000",
        gallery: [
          "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Apple Watch Ultra / Series 9", price: "Official Warranty", period: "unit", capacity: "GPS / Cellular", badge: "Premium", desc: "Heart rate, ECG, blood oxygen, always-on Retina display." },
          { name: "Samsung Galaxy Watch 6", price: "Market Best Price", period: "unit", capacity: "Bluetooth / LTE", badge: "Android", desc: "Body composition analysis, sleep coaching, sapphire crystal." },
        ],
        about: "Enhance your lifestyle and productivity with the latest premium smartwatches with heart rate telemetry, GPS navigation, and cellular connectivity.",
      },
      {
        slug: "wireless-audio",
        name: "Wireless Audio & Earbuds",
        desc: "Active noise-cancelling AirPods, Galaxy Buds, and high-fidelity Bluetooth audio.",
        tag: "Hi-Res Audio",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 18,500",
        gallery: [
          "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Apple AirPods Pro (2nd Gen with USB-C)", price: "PKR 62,000", period: "sealed unit", capacity: "Active Noise Cancel", badge: "Pro Audio", desc: "2x active noise cancellation, spatial audio, MagSafe charging case." },
          { name: "Samsung Galaxy Buds 2 Pro", price: "PKR 38,000", period: "sealed unit", capacity: "24-bit Hi-Fi", badge: "Hi-Res", desc: "Ergonomic fit, 360 audio, IPX7 water resistance." },
        ],
        about: "Immerse yourself in crystal clear music and seamless calls with industry-leading active noise-cancelling wireless earphones.",
      },
      {
        slug: "power-banks",
        name: "High-Capacity Power Banks",
        desc: "Ultra-compact magnetic wireless batteries and heavy-duty portable power banks.",
        tag: "Travel Power",
        image: "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?w=800&q=80&auto=format&fit=crop",
        price: "Starting from PKR 5,500",
        gallery: [
          "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "10,000mAh Magnetic Wireless MagSafe Battery", price: "PKR 6,800", period: "unit", capacity: "10,000 mAh", badge: "Travel Essential", desc: "Snaps magnetically to back of phone, fold-out kickstand." },
          { name: "20,000mAh 65W Laptop Power Bank", price: "PKR 12,500", period: "unit", capacity: "20,000 mAh", badge: "Laptop & Phone", desc: "Charges MacBook, Dell XPS, and multiple phones simultaneously." },
        ],
        about: "Never run out of power on the go. High capacity, airline safety-compliant battery packs that charge your devices at lightning speed.",
      },
      {
        slug: "express-delivery",
        name: "Same-Day Doorstep Delivery",
        desc: "Instant ordering via WhatsApp with express delivery to your home, office, or hotel.",
        tag: "Express Dispatch",
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80&auto=format&fit=crop",
        price: "Free on Orders over PKR 10,000",
        gallery: [
          "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1600&q=85&auto=format&fit=crop",
        ],
        options: [
          { name: "Express 2-Hour Delivery", price: "PKR 500", period: "within city", capacity: "Immediate Dispatch", badge: "Super Fast", desc: "Rider delivers sealed item directly to your doorstep." },
          { name: "Standard Same-Day Delivery", price: "Free", period: "orders 10k+", capacity: "Scheduled", badge: "Popular", desc: "Delivered within 4 to 6 hours with cash on delivery or online bank transfer." },
        ],
        about: "Enjoy hassle-free shopping with verified same-day dispatch. Inspect your sealed package before payment.",
      },
    ],
    faqs: [
      { q: "Are all products original and under warranty?", a: "Yes, 100% of our smartphones and accessories are authentic, brand new, and sealed with warranty." },
      { q: "How fast is delivery?", a: "Same-day express delivery within 2 to 4 hours for local orders." },
      { q: "How can I place an order?", a: "Simply tap the WhatsApp button with the product name for instant order confirmation." },
    ],
  },
];

